# Generated by Django 5.0.6 on 2024-07-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_login_remove_register_user_id_register_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email_id',
            new_name='email',
        ),
    ]
