# Generated by Django 5.0.6 on 2024-07-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_email_id_register_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email_id',
            new_name='email',
        ),
    ]
