# Generated by Django 5.0.6 on 2024-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_rename_email_id_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
