# Generated by Django 5.0.6 on 2024-07-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='email',
            new_name='email_id',
        ),
    ]
