# Generated by Django 5.0.6 on 2024-07-28 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_newuser_first_name_newuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
